services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-henrique}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-segredo}
      POSTGRES_DB: ${POSTGRES_DB:-superprojetao}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-henrique} -d ${POSTGRES_DB:-superprojetao}"]
      interval: 10s
      retries: 4
      start_period: 50s
      timeout: 15s

  app:
    image: henriquerb1/api-computacao-em-nuvem:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-henrique}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-segredo}
      POSTGRES_DB: ${POSTGRES_DB:-superprojetao}
      SECRET_KEY: ${SECRET_KEY:-hidsa53sdadshDADBJSKsd1d2as1d3}
      ALGORITHM: ${ALGORITHM:-HS256}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
    depends_on:
        db:
          condition: service_healthy
          restart: true
    ports:
      - "8000:8000"
