version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-henrique}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-segredo}
      POSTGRES_DB: ${POSTGRES_NAME:-superprojetao}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      #- ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  app:
    image: henriquerb1/api-computacao-em-nuvem:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-henrique}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-segredo}
      POSTGRES_DB: ${POSTGRES_NAME:-superprojetao}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      SECRET_KEY: ${SECRET_KEY:-hidsa53sdadshDADBJSKsd1d2as1d3}
      ALGORITHM: ${ALGORITHM:-HS256H}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data:
