apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "henrique"
            - name: POSTGRES_PASSWORD
              value: "segredo"
            - name: POSTGRES_DB
              value: "superprojetao"

---

apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: henriquerb1/api-computacao-em-nuvem:latest
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              value: "henrique"
            - name: POSTGRES_PASSWORD
              value: "segredo"
            - name: POSTGRES_DB
              value: "superprojetao"
            - name: SECRET_KEY
              value: "hidsa53sdadshDADBJSKsd1d2as1d3"
            - name: ALGORITHM
              value: "HS256"
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              value: "30"

---

apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 8000
  
